### ISSUE TITLE
"Command Suggestions" setting gets turned off

### ISSUE THREAD

**Issue by maskersss** [KingContaria/StandardSettings#3] opened 2022-08-21 13:35 UTC
In versions 1.2.1 and 1.2.1.1, whenever I reset, the setting "Command Suggestions" (in Options -> Chat Settings in bottom left) automatically gets turned off. It doesn't happen if I join an already existing world. It also doesn't happen in version 1.2.0.

**Comment by contariaa** [comment] 2022-08-22 00:50
that sounds like you have the line 'autoSuggestions:false' in your standardoptions.txt, if not, could you send me the file?

**Comment by maskersss** [comment] 2022-08-22 08:13
No, I tested it with a file that just says "autoJump:false", but here's what was in the file initially: https://textsaver.flap.tv/lists/4zxt .
I believe that if there's no line "autoSuggestions:...", the mod just assumes there is "autoSuggestions:false", because when I added "autoSuggestions:true" to the file, it worked fine.
Also I believe that it wasn't initially in the file because it wasn't in the older versions of standardsettings, and when I changed the mod to a newer version, it obviously didn't add it.

**Comment by contariaa** [comment] 2022-08-24 14:37
i assume you're playing on minecraft version 1.16.1?

**Comment by contariaa** [comment] 2022-08-24 14:43
could you also send me a video of the bug happening because i can't seem to reproduce the issue

**Comment by maskersss** [comment] 2022-08-24 16:13
ok, i did some more testing, and from what i see if there's no line "autoSuggestions:...", but there's "autoJump:...", the autojump setting is also getting applied to autosuggestions.
and vice versa – if there isn't an autojump setting, but there's autosuggestions, autosuggestions gets applied to autojump

**Comment by maskersss** [comment] 2022-08-24 16:13
if you still want me to record the video, feel free to ask

**Comment by maskersss** [comment] 2022-08-24 16:20
also yes, 1.16.1

**Comment by contariaa** [comment] 2022-08-24 16:34
oooooh i just checked the code, turns out i forgot to add one 'break' line in the switch statement when making it java 8 compatible, will be fixed in the next update whenever that comes out!

**Closed as completed** 2022-08-24 16:38 UTC
