### ISSUE TITLE
[1.8.9] Incorrect behavior on gui sizes on old worlds

### ISSUE THREAD

**Issue by tildejustin** [KingContaria/StandardSettings#4] opened 2022-08-22 23:40 UTC
Regardless of whether standardsettings.txt has guiScale set or not, the mod always resets gui scale to auto if an old world is loaded first thing after launch.

**Comment by contariaa** [comment] 2022-08-24 14:36
oh thanks for the issue i know what the problem is here! will be fixed in the next update, idk when that will come out tho

**Comment by contariaa** [comment] 2022-08-29 20:22
should be resolved in this prerelease:
https://github.com/KingContaria/StandardSettings/releases/tag/v1.2.2-pre1

**Comment by tildejustin** [comment] 2022-08-29 20:29
I can test in a couple hours

**Comment by tildejustin** [comment] 2022-08-30 00:25
I'm getting some really wierd behavior when dying with hardcore after loading up an old world first thing. It doesn't delete the world and the timer continues on the home screen while sounds from the world still play. When you join back in it takes you to before you died.

**Comment by tildejustin** [comment] 2022-08-30 00:50
hmm that might just be terrible vanilla behavior. It looks like vanilla doesn't delete worlds when you hit the delete button. Is this true?

**Comment by tildejustin** [comment] 2022-08-30 00:53
settings are being reset when joining an old world, is this intended?

**Comment by contariaa** [comment] 2022-08-30 10:03
can you show me your mods folder?

**Comment by contariaa** [comment] 2022-08-30 10:10
okay so i tested it a bit myself, and it turns out that the issues with sound still playing and the world not getting deleted are a vanilla bug (i tested it without any mods, not even installed fabric) so i assume the timer still playing is just a sideproduct from that bug and has nothing to do with standardsettings.
i cannot however reproduce the settings being changed on old worlds, are you sure you dont still have an older version of standardsettings in your mod folder?

**Comment by contariaa** [comment] 2022-08-30 10:31
https://bugs.mojang.com/browse/MC-30646

**Comment by tildejustin** [comment] 2022-08-30 17:02
Yeah I can't reproduce settings being changed on an old world, looks good to me!

**Comment by contariaa** [comment] 2022-08-30 18:03
okay, thanks for your testing its very appreciated! :)

**Closed as completed by contariaa** 2022-08-30 18:03 UTC
